server:
  servlet: # 建议与name一致
    context-path: /spring-boot-websocket
  port: 9095

spring:
  application:
    name: spring-boot-websocket-mq
  # RabbitMQ 配置项，对应 RabbitProperties 配置类
  rabbitmq:
    host: ${REMOTE_URL:127.0.0.1}
    port: 5672
    username: guest
    password: guest
    # 设置 Confirm 类型为 CORRELATED 确认消息已发送到交换机(Exchange)。
    publisher-confirm-type: correlated
    # 确认消息已发送到队列(Queue)
    publisher-returns: true
    virtual-host: /test

# 日志
logging:
  level:
    root: info
    top.somliy: info
project:
  websocket:
    timeoutPeriod: 20000
    textMessageSize: 1000000
    binaryMessageSize: 1000000