<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>top.somliy.demo</groupId>
    <artifactId>somliy-spring-boot-demo</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>pom</packaging>

    <name>somliy-spring-boot-demo</name>
    <description>somliy-spring-boot-demo</description>

    <properties>
        <java.version>1.8</java.version>
    </properties>

    <modules>
        <module>spring-boot-mq-kafka</module>
        <module>spring-boot-mq-rabbit-mq</module>
        <module>spring-boot-date-serialize</module>
        <module>spring-boot-current-limiting</module>
    </modules>

</project>
