server:
  port: 9091

spring:
  application:
    name: spring-boot-mq-rabbit-mq-simple

  # RabbitMQ 配置项，对应 RabbitProperties 配置类
  rabbitmq:
    host: ${REMOTE_URL:127.0.0.1}
    port: 5672
    username: guest
    password: guest
    # 设置 Confirm 类型为 CORRELATED 确认消息已发送到交换机(Exchange)。
    publisher-confirm-type: correlated
    # 确认消息已发送到队列(Queue)
    publisher-returns: true
    virtual-host: /test