server:
  servlet: # 建议与name一致
    context-path: /spring-boot-websocket
  port: 9095

logging:
  level:
    top: debug
    org:
      springframework:
        kafka: debug
      apache:
        kafka: debug
    root: debug

project:
  websocket:
    timeoutPeriod: 20000
    textMessageSize: 1000000
    binaryMessageSize: 1000000